id: P008032
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC368
  title: 'ཆུ་གླང་ཝང་ཤུ་ཚུར་ཕུལ་གྱི་དེབ་གཞུང་། '
  author: ''
  volumes:
    be56772edd974c38ad43cb87fb0c9c90:
      image_group_id: I4PD4429
      title: ''
      volume_number: 1
      total_pages: 372
ebook_metadata:
  title: 'ཆུ་གླང་ཝང་ཤུ་ཚུར་ཕུལ་གྱི་དེབ་གཞུང་། '
  author: ''
  sku: P008032
  cover: cover.jpg
  layers:
  - pagination
