id: P008032
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1AC368
  title: 'ཆུ་གླང་ཝང་ཤུ་ཚུར་ཕུལ་གྱི་དེབ་གཞུང་། '
  author: ''
  volumes:
    3117483758c7489d8a0b2f2f4a978700:
      image_group_id: I4PD4429
      title: Volume 1 of chu glang wang shu tshur phul gyi deb gzhung /
      volume_number: 1
      total_pages: 372
      base_file: v001.txt
